### PR TITLE
Compact virtual host template

### PR DESCRIPTION
**Pull request by DavidePrincipi**
Expand multiple server names as a single VirtualHost stanza, using
Apache [ServerAlias](https://httpd.apache.org/docs/2.4/mod/core.html#serveralias) directive.

### CODE REVIEW

**Comment by gsanchietti** [comment]
I'd like to not change anything since the configuration of Apache is too much choosy.
The modification is almost cosmetic but changes a lot the actual configuration without any real advantage.

**Review by gsanchietti — CHANGES_REQUESTED** [review]
I'd like to not change anything since the configuration of Apache is too much choosy.
The modification is almost cosmetic but changes a lot the actual configuration without any real advantage.

**Comment by stephdl** [comment]
same for me, workable, why change it, except to add more features. This change might break my work for nethserver-awstats :p

**Comment by DavidePrincipi** [comment]
Ok, we can close it!

**Pull request closed without merging**
